# Generated by Django 2.1.8 on 2019-06-15 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190615_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='total_payment',
            field=models.FloatField(default=0),
        ),
    ]
